### ISSUE TITLE
send text with link for a link card (from index.php) doesn't work

### ISSUE THREAD

**Issue by hayglow** [williamsdb/php2Bluesky#8] opened 2024-10-25 17:13 UTC
I've set up php2Bluesky on my laptop. While
- send a text only post with link
- send an image with text and a link

work fine,

- send text with link for a link card

doesn't.

The first two post text, link (and image) to my Bluesky, the third gives me this:

in Browser:
stdClass Object ( [error] => InvalidRequest [message] => Invalid app.bsky.feed.post record: Record/embed/external/thumb should be a blob ref )

or on Terminal:
PHP Warning:  Undefined variable $image in /var/www/html/post2bsky/williamsdb/functions.php on line 309
stdClass Object
(
    [error] => InvalidRequest
    [message] => Invalid app.bsky.feed.post record: Record/embed/external/thumb should be a blob ref
)

I have set $link = 'https://example.com/';

If I delete line 309 in functions.php ('thumb' => $image,) it posts a card to my Bluesky. But - obviously - no image is shown. Also the card is missing the image referenced in the linked HTML as og:image. I tried this with another $link (where an image is referenced, because example.com hasn't).

Do you have any advice?

**Comment by hayglow** [comment] 2024-10-25 17:27
If I delete line 309 in functions.php ('thumb' => $image,) it posts a card to my Bluesky. But - obviously - no image is shown. Also the card is missing the image referenced in the linked HTML as og:image.

I tried this with another $link (where an image is referenced, because example.com hasn't).

**Comment by PDelahanty** [comment] 2024-10-25 18:37
This response seems to make the issue pretty clear...
`PHP Warning: Undefined variable $image in /var/www/html/post2bsky/williamsdb/functions.php on line 309
stdClass Object`

Is $image defined? If you don't have an image, try defining it like $image = '';

**Comment by hayglow** [comment] 2024-10-25 18:56
I left index.php pretty much untouched. So I have also
`$response = post_to_bluesky($connection, $text, '', $link);`
I defined $handle, $password, $filename, $link and $text. This works fine for "send a text only post with link" and "send an image with text and a link".
But when I use "send text with link for a link card" from index.php I get the above. I also tried to inforporate 
`$image = upload_media_to_bluesky($connection, $filename, $fileUploadDir);` or
`$image = '';`
No luck with both.

**Comment by williamsdb** [comment] 2024-10-25 19:46
Hi,

I think that you are saying that the link card with text isn't working, is that right?

I have just tried the following example which worked fine for me:

```
    $link = 'https://twit.tv/shows/this-week-in-google/episodes/743';
    $text = 'Hey look! four images!';
    
    // connect to Bluesky API
    $connection = bluesky_connect($handle, $password);

    // send text with link for a link card
    // if you specifiy both media and link the latter takes precedence
    $response = post_to_bluesky($connection, $text, '', $link);
    print_r($response);
```

Running from the command line I see this:

```
neilthompson@Neils-MacBook-Pro src % php test.php
stdClass Object
(
    [uri] => at://did:plc:vo4tztpeggwuadrttch2fseo/app.bsky.feed.post/3l7edgxijit2p
    [cid] => bafyreibfbqnnxrx5oeczm4emnuzdxey5b3gt23mnlt3pyw3d4czwafzo5u
    [commit] => stdClass Object
        (
            [cid] => bafyreigs2yyuvyucbolqcsrn6ei27nxmlbr2lqq5sxmgc3fwoepwrljc5e
            [rev] => 3l7edgxiof32p
        )

    [validationStatus] => valid
)

```

You can [see the result here](https://bsky.app/profile/spokenlikeageek.com/post/3l7edgxijit2p).

Perhaps if you can paste the code you are running or even just the url of the link that you are trying to use as a card I can try and see what I get.

**Comment by hayglow** [comment] 2024-10-26 09:22
Hi williamsdb, 

I just tried to use your code. It worked.

It is worth noting, that before I got it working I had to add _php-dom_ and _php-gd_ to my PHP-installation. Maybe you could add the in your Prerequisites section?

It also worked with a couple of other URLs. But there seems to be an issue with my specific URL. I tried `$link = 'https://www.greenjobs.de';` and got the following:

`PHP Warning:  Undefined variable $mime in /var/www/html/post2bsky/williamsdb/functions.php on line 63
PHP Warning:  Undefined property: stdClass::$blob in /var/www/html/post2bsky/williamsdb/functions.php on line 65
stdClass Object
(
    [error] => InvalidRequest
    [message] => Invalid app.bsky.feed.post record: Record/embed/external/thumb should be a blob ref
)
`

I understand, that $mime is not defined and that there is a problem with a blob ref. So do I need to make any changes to the image or website itself?

If I post this link (https://www.greenjobs.de) via the Bluesky web-app the link card shows up fine.

**Comment by williamsdb** [comment] 2024-10-26 14:54
Hi

Thanks for the update. I have now been able to reproduce the issue given the url your provided. I haven't had a chance to check it yet but I suspect that the issue is that the page, https://www.greenjobs.de, doesn't have an image that can be used for the link card. I need to double check that this is in fact the issue and if it is decide what to do which will depend on what the api expect. Give me a couple of days to work through it.

Neil

**Comment by williamsdb** [comment] 2024-10-27 19:31
Hi

I have fixed the issue and pushed a fix for it. If you either pull the change or download the latest functions.php you'll be all sorted.

In case you wanted to know the issue... When I look for the mime type of the image file I request the headers and look for a header of Content-Type but the image from the link you provided had the header all in lower case:

`[content-type] => image/png`

So now I have added this as a case too and updated the readme.

Thanks!

N

**Closed by williamsdb** 2024-10-27 19:31 UTC

**Comment by hayglow** [comment] 2024-10-28 08:28
Thanks for the update. After implementing the new version of functions.php I got the following error for **every URL** I tested:

`PHP Warning:  mime_content_type(): Failed identify data 0:(null) in /var/www/html/post2bsky/williamsdb_new/functions.php on line 60
PHP Warning:  Undefined property: stdClass::$blob in /var/www/html/post2bsky/williamsdb_new/functions.php on line 65
stdClass Object
(
    [error] => InvalidRequest
    [message] => Invalid app.bsky.feed.post record: Record/embed/external/thumb should be a blob ref
`

So I compared the new functions.php to the old one and fiddled around with it. I left the new check for content-type (lines 55 and 56 of **new** functions.php) untouched, but re-inserted the `}else{` (line 59 of the **old** functions.php).

Works for me now with every URL I tested.

Thanks for fixing the initial issue! It is appreciated.

**Comment by williamsdb** [comment] 2024-10-28 14:31
Yes sorry that was a bug as I was rushing. Should be fixed now. Thanks for the heads up. N
